# Hello, MT3... Let's see if we can revive you, and make you easier to build...
# It's been a long time. Hope this works....

  
language: cpp
compiler:
 - gcc
# - clang # Once someone figures this out...

addons:
  apt:
    packages:
    - cmake
    - libc6-dev-i386
    - libc6-dev-amd64

#before_install:
# What do we need here, if anything?

install:
 - cmake .
 - make
