//---------------------------------------------------------------------------
// This file has been generated by MadTracker 3 GUI Editor *DO NOT EDIT!*
//---------------------------------------------------------------------------
#ifndef __MT3RESH__
#define __MT3RESH__
//---------------------------------------------------------------------------
// Windows IDs
//---------------------------------------------------------------------------
#define MTW_pattern                0
#define  MTC_page                  0    // MTWindow
#define  MTC_tabcontrol            1    // MTTabControl
#define  MTC_epname                0    // MTItemComboBox
#define MTW_instrument             1
#define  MTC_page                  0    // MTWindow
#define  MTC_tabcontrol            1    // MTTabControl
#define  MTC_einame                0    // MTItemComboBox
#define MTW_oscillator             2
#define  MTC_eoname                0    // MTItemComboBox
#define MTW_sequencer            100
#define MTW_main2                128
#define  MTC_check                 0    // MTCheckBox
#define  MTC_check                 0    // MTCheckBox
#define  MTC_check                 0    // MTCheckBox
#define  MTC_check                 0    // MTCheckBox
#define  MTC_check                 0    // MTCheckBox
#define  MTC_check                 0    // MTCheckBox
#define  MTC_bconfig             500    // MTButton
#define  MTC_bnetwork            400    // MTButton
#define  MTC_bhelp               300    // MTButton
#define  MTC_btools              202    // MTButton
#define  MTC_bview               201    // MTButton
#define  MTC_binfo               200    // MTButton
#define  MTC_bfile               101    // MTButton
#define  MTC_bnew                100    // MTButton
#define  MTC_panel1               10    // MTPanel
#define  MTC_brecord             800    // MTButton
#define  MTC_bplaypause          701    // MTButton
#define  MTC_bstop               700    // MTButton
#define  MTC_bend                603    // MTButton
#define  MTC_bfastforward        602    // MTButton
#define  MTC_brewind             601    // MTButton
#define  MTC_bbegin              600    // MTButton
#define  MTC_panel2               11    // MTPanel
#define  MTC_list2                 2    // MTUserList
#define  MTC_list1                 1    // MTUserList
#define MTW_file                 256
#define  MTC_bload                 7    // MTButton
#define  MTC_efilename             3    // MTEdit
#define  MTC_label                 0    // MTLabel
#define  MTC_cfolder               1    // MTItemComboBox
#define  MTC_efilter               4    // MTItemComboBox
#define  MTC_label                 0    // MTLabel
#define  MTC_file                  2    // MTFileListBox
#define MTW_main               65535
#define  MTC_mhelp                 5    // MTButton
#define  MTC_mwindow               4    // MTButton
#define  MTC_mmodule               3    // MTButton
#define  MTC_medit                 2    // MTButton
#define  MTC_mfile                 1    // MTButton
//---------------------------------------------------------------------------
// Texts IDs
//---------------------------------------------------------------------------
#define MTT_madtracker             0
#define MTT_copyright              1
#define MTT_freeslot               2
//---------------------------------------------------------------------------
// Bitmaps IDs
//---------------------------------------------------------------------------
#define MTB_mt3logo                1
//---------------------------------------------------------------------------
#endif
