//---------------------------------------------------------------------------
// This file has been generated by MadTracker 3 GUI Editor *DO NOT EDIT!*
//---------------------------------------------------------------------------
#ifndef __MTObjectsRESH__
#define __MTObjectsRESH__
//---------------------------------------------------------------------------
// Windows IDs
//---------------------------------------------------------------------------
#define MTW_monitor                0
#define  MTC_chanmonitor           2    // MTCustomControl
#define  MTC_channels              0    // MTWindow
#define  MTC_cpumonitor            1    // MTCustomControl
#define  MTC_cpu                   0    // MTWindow
#define  MTC_tc                    0    // MTTabControl
#define MTW_pattern                1
#define  MTC_label                 0    // MTLabel
#define  MTC_data                100    // MTCustomWincontrol
#define MTW_instrument             2
#define  MTC_lvibrato              0    // MTLabel
#define  MTC_epanz                 0    // MTEdit
#define  MTC_epany                 0    // MTEdit
#define  MTC_ppanz                 0    // MTSlider
#define  MTC_ppany                 0    // MTSlider
#define  MTC_epanx                 0    // MTEdit
#define  MTC_ppanx                 0    // MTSlider
#define  MTC_lpan                  0    // MTLabel
#define  MTC_evolume               0    // MTEdit
#define  MTC_lvolume               0    // MTLabel
#define  MTC_pvolume               0    // MTSlider
//---------------------------------------------------------------------------
// Texts IDs
//---------------------------------------------------------------------------
#define MTT_module                 0
#define MTT_pattern                1
#define MTT_automation             2
#define MTT_instrument             3
#define MTT_oscillator             4
#define MTT_track                  5
#define MTT_effect                 6
#define MTT_lock1                200
#define MTT_lock2                201
#define MTT_lock_module           50
#define MTT_lock_pattern          51
#define MTT_lock_automation       52
#define MTT_lock_instrument       53
#define MTT_lock_oscillator       54
#define MTT_lock_track            55
#define MTT_noaccess              60
#define MTT_can_read             100
#define MTT_can_write            101
#define MTT_can_copy             102
#define MTT_can_delete           103
#define MTT_can_play             104
#define MTT_master                 7
#define MTT_lock_effect           56
#define MTT_lock_object           57
#define MTT_nextline             500
#define MTT_prevline             501
#define MTT_nexttrack            502
#define MTT_prevtrack            503
#define MTT_firstline            504
#define MTT_lastline             505
#define MTT_nextbeat             506
#define MTT_prevbeat             507
#define MTT_right                508
#define MTT_left                 509
#define MTT_delete               510
#define MTT_removecell           511
#define MTT_removeline           512
#define MTT_insertcell           513
#define MTT_insertline           514
//---------------------------------------------------------------------------
#endif
